### ISSUE TITLE
Content script timing issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1221]
There are multiple issues caused by elements added by the stealth script and content script.

For now, the only viable solution I see is to add a couple of exceptions to the content script itself.

Here is the list of issues:
* [x] [muve.pl](https://github.com/AdguardTeam/CoreLibs/issues/767)
* [x] [mail.yahoo.com](https://github.com/AdguardTeam/CoreLibs/issues/1193)
* [x] [map.baidu.com](https://github.com/AdguardTeam/CoreLibs/issues/1183)

* * *

Next ones can be fixed only by filters:
* [x] [partner.ebay.com](https://github.com/AdguardTeam/CoreLibs/issues/1204)
* [x] [simkl.com](https://github.com/AdguardTeam/CoreLibs/issues/1027)
* [x] [fuqer.com](https://github.com/AdguardTeam/CoreLibs/issues/1182) (NSFW)
* [x] [ats.megapbx.ru](https://github.com/AdguardTeam/AdguardFilters/issues/46463) - account is required

**Comment by Alex-302** [comment]
Another one(added to the list)
https://github.com/AdguardTeam/AdguardFilters/issues/46463
Important: disable `@@||ats.megapbx.ru^$elemhide,jsinject` exclusion

**Comment by Alex-302** [comment]
Probably the same issue: https://planeta.ru/
https://github.com/AdguardTeam/AdguardFilters/issues/46920
Reproduced on Mac only, with disabled filters and `$document` exclusion

**Comment by Alex-302** [comment]
It seems the similar issue
https://github.com/AdguardTeam/AdguardFilters/issues/48214
but not reproduced on my end.
