### ISSUE TITLE
Switch to BoringSSL

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1223]
Aside from obvious advantages and the fact that it gets new features earlier than openssl, it will also fix a couple of other issues (we will have to test this!):

* [ ] [mcdonalds.fr issue](https://github.com/AdguardTeam/CoreLibs/issues/878)
* [ ] [re-store.ru issue](https://github.com/AdguardTeam/CoreLibs/issues/1084)
* [ ] [svyaznoy.ru issue](https://github.com/AdguardTeam/CoreLibs/issues/674)
* [ ] [Firefox onlinetrade.ru issue](https://github.com/AdguardTeam/CoreLibs/issues/1232)
* [ ] [wind.gr issue](https://github.com/AdguardTeam/CoreLibs/issues/1124)

**Comment by optomux** [comment]
Why not WolfSSL?

**Comment by ameshkov** [comment]
Boring receives new TLS features faster than any other library
