### ISSUE TITLE
Tracking issue for sites broken by DPI protection

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#1645]
When CoreLibs 1.9.69+ will be deployed to AG products, this list may be used for adding $stealth exclusions.

- [ ] [https://www.ghxi.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.ghxi.com%2F)
- [ ] [http://go.gov.il](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fgo.gov.il)
- [ ] [https://www.thegioididong.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.thegioididong.com%2F)
- [ ] [https://tvr.by/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ftvr.by%2F)
- [ ] [https://pravo.by/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fpravo.by%2F)
- [ ] [https://beltelecom.by/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fbeltelecom.by%2F) but [https://my.beltelecom.by/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fmy.beltelecom.by%2F) works [(comment)](https://github.com/AdguardTeam/CoreLibs/issues/1615#issuecomment-1117541499)
- [ ] [https://blog.torproject.org/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fblog.torproject.org%2F) but [https://www.torproject.org/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.torproject.org%2F) works [(comment)](https://github.com/AdguardTeam/CoreLibs/issues/1615#issuecomment-1117541499)
- [ ] https://github.com/AdguardTeam/CoreLibs/issues/1634
- [ ] https://github.com/AdguardTeam/CoreLibs/issues/1636
- [ ] https://github.com/AdguardTeam/CoreLibs/issues/1639

**Comment by zubrRB** [comment]
У всех или почти всех сайтов списка ошибка связана с механизмом ограничения по IP-адресу, включая блог Tor Project.

**Comment by piquark6046** [comment]
There is a new issue.
 - https://github.com/AdguardTeam/AdguardFilters/issues/121547
 
PS. What about making `$dpi` instead of `$stealth` for many users in some regions like South Korea?

**Comment by sfionov** [comment]
@piquark6046 We have an issue about specifying separate features in $stealth rules, so you will be able to use `$stealth=dpi`

https://github.com/AdguardTeam/CoreLibs/issues/1224

**Comment by zubrRB** [comment]
I have this site opened without problems with `Protect from DPI`. Apparently, the same dependence on the IP-address.

**Comment by mrrtarlan** [comment]
@sfionov +bankrespublika.az

**Comment by zubrRB** [comment]
https://kun.uz/ru `ERR_SSL_PROTOCOL_ERROR / ERR_CONNECTION_RESET / ERR_CONNECTION_CLOSED`

**Comment by zubrRB** [comment]
https://www.mil.by/ `ERR_CONNECTION_RESET`

**Comment by jellizaveta** [comment]
Exclusion for all domains from this issue was added in stealth whitelist. Please disable the Base filter before checking this problem.

**Comment by Eugene-Savenko** [comment]
- [ ] https://www.suwonlib.go.kr/ 

reported by: helpdesk ID 619136.

**Comment by zloyden** [comment]
@Eugene-Savenko fixed, update should be available in 1-2 hours.
Now you can report about such issues to https://github.com/AdguardTeam/AdguardFilters repo.

**Comment by sfionov** [comment]
@zloyden Since there was no apps releases with working `$stealth` exclusions for DPI, and new CL1.10 nightlies have `$stealth=dpi` rules, you may use `$stealth=dpi` in rules.

**Comment by zloyden** [comment]
@sfionov maybe later I will change the rules when the release versions will get new CL1.10. I will add new `TODO` comment.
For instance, AdGuard for Windows does not have it now and your rule is incorrect.
For now, rule with `$stealth` helps.

**Comment by zubrRB** [comment]
Данные изменения `$stealth=dpi` внедрены с версии AdGuard 7.11 nightly 2. Проверено — работает.

**Comment by zloyden** [comment]
Most users do not use the nightly version.

**Comment by sfionov** [comment]
@zloyden Okay, I didn't know that that CL1.9.69 had reached the stable app.

**Comment by piquark6046** [comment]
- [ ] https://www.lghellovision.net/

 Reported by an anon https://listauthorschat.slack.com/archives/C010PK19W78/p1659441521291449

**Comment by sfionov** [comment]
https://www.dienmayxanh.com/

https://github.com/AdguardTeam/AdguardForAndroid/issues/4211

**Comment by trmdi** [comment]
> https://www.dienmayxanh.com/
> 
> [AdguardTeam/AdguardForAndroid#4211](https://github.com/AdguardTeam/AdguardForAndroid/issues/4211)

https://www.thegioididong.com/ too.

**Comment by sfionov** [comment]
@trmdi It is already in list: https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/whitelist_stealth.txt#L23

It is recommended to upgrade to version 3.6.9 where these exclusions work.

**Comment by zloyden** [comment]
> [dienmayxanh.com](https://www.dienmayxanh.com/)

Added to master, update should be available in 1-2 hours.

**Comment by sfionov** [comment]
ais.osym.gov.tr

https://github.com/AdguardTeam/AdguardForWindows/issues/4327

**Comment by AdamWr** [comment]
Another one - https://github.com/AdguardTeam/AdguardFilters/issues/125993
 [https://www.mojedatovaschranka.cz/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.mojedatovaschranka.cz%2F)

**Comment by trmdi** [comment]
Another one: www.bachhoaxanh.com

**Comment by zloyden** [comment]
@trmdi added to our filters.

**Comment by trmdi** [comment]
> @trmdi It is already in list: https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/whitelist_stealth.txt#L23
> 
> It is recommended to upgrade to version 3.6.9 where these exclusions work.

Hi, why is blocked again today? It works normally when turning of the Stealth mode.

> www.thegioididong.com

**Comment by trmdi** [comment]
I just found that `thegioididong.com` is already in the list:

https://github.com/AdguardTeam/AdguardFilters/blob/425669ced45729794a5d75e2554b959fb0a7bf2e/EnglishFilter/sections/allowlist_stealth.txt#L26

but it's not in: https://filters.adtidy.org/android/filters/2_optimized.txt
Maybe a bug?

**Comment by zubrRB** [comment]
https://www.mpt.gov.by

**Comment by Oniqqqq** [comment]
ric-ul.ru

**Comment by Oniqqqq** [comment]
http://ric-ul.ru

**Comment by zloyden** [comment]
@Oniqqqq is that caused by `DPI protection`? I can't reproduce this on my end.

**Comment by Oniqqqq** [comment]
@zloyden one of our users reported that only when DPI protection is enabled, the site stops working. My colleagues from support team also saying that the issue has been reproduced.

**Comment by zloyden** [comment]
I got it, added to our filters.

**Comment by piquark6046** [comment]
- https://github.com/List-KR/List-KR/issues/485

**Comment by sfionov** [comment]
MyBell application for Android

https://github.com/AdguardTeam/AdguardForAndroid/issues/4221#issuecomment-1237435147

**Comment by grumaxxx** [comment]
www.wko.at - https://github.com/AdguardTeam/CoreLibs/issues/1666

**Comment by Alex-302** [comment]
+1 p30download.ir
https://github.com/AdguardTeam/AdguardFilters/issues/130039

**Comment by piquark6046** [comment]
- seoulland.co.kr (https://github.com/List-KR/List-KR/commit/b286c49b576b5d67f634c032251354434d1970d3)

**Comment by piquark6046** [comment]
- https://github.com/AdguardTeam/AdguardFilters/issues/133326

**Comment by piquark6046** [comment]
- https://covid19m.kdca.go.kr/

**Comment by Gittyperson** [comment]
These two are also broken by DPI (related websites - same company):

https://www.tovima.gr/
https://www.tanea.gr/

**Comment by Taewan-P** [comment]
This page is broken as well.

- https://www.letskorail.com

**Comment by piquark6046** [comment]
@Taewan-P Created new PR.

**Comment by Citrinae-Lime** [comment]
These sites are also broken:

- [oktatas.hu](https://www.oktatas.hu)
- [kifir2.kir.hu](https://kifir2.kir.hu/TTJegyzekKereso)

**Comment by ihurin** [comment]
One more website:
kt.com

Initially reported in ZD ticket #742005

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/CoreLibs/issues/1645#issuecomment-1493677404
I will check that.

**Comment by piquark6046** [comment]
@ihurin Does your issue occur when you log in to Korea Telecom?

**Comment by sfionov** [comment]
belkagomel.by #1672

**Comment by ameshkov** [comment]
We now have stealth=dpi modifier, can't we fix all these issues in the tracking protection list?

**Comment by piquark6046** [comment]
New domain: egmobile.co.kr

**Comment by piquark6046** [comment]
New domain: q-net.or.kr

**Comment by ameshkov** [comment]
@Alex-302 what about now? :)

**Comment by Alex-302** [comment]
@ameshkov We use it now
https://github.com/AdguardTeam/AdguardFilters/commit/21a8f1a70db7c85e1cdfa3063a0ad8e162ca21e2
The problem is that these rules are often removed from optimized filters for AdGuard for Android, and we forced to use `!+ NOT_OPTIMIZED` for each of these rules (no equivalent directive, or switch for using full filters for modern Android devices).

**Comment by ameshkov** [comment]
@Alex-302 these rules shouldn't be optimized indeed, we'll resolve it in another task (see ADG-7346)

**Comment by ameshkov** [comment]
Closing this one since now all CoreLibs-based products support `$stealth=dpi`
