### ISSUE TITLE
Userscripts checklist

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#204]
Checked is working, unchecked is not.

* [x] https://github.com/AdguardTeam/AdguardAssistant
* [x] https://github.com/AdguardTeam/PopupBlocker
* [x] https://greasyfork.org/en/scripts/378070-adblock-for-facebook
* [x] https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes
* [x] https://github.com/StylishThemes/GitHub-Dark-Script/
Currently it's not working because of GM4 async API #170
* [ ] See the details here: https://github.com/AdguardTeam/AdguardFilters/issues/18815#issuecomment-427702219
[Taiwanese script](https://greasyfork.org/en/scripts/370155-%E8%B7%B3%E9%81%8E%E5%8B%95%E7%95%AB%E7%98%8B%E5%BB%A3%E5%91%8A/code) is not working:
https://uploads.adguard.com/Windows_10_32_bit_rus_2019-06-27_19-16-14.png

upd:
* [ ] https://raw.githubusercontent.com/solymosi/npu/master/npu.user.js - here is a link to [the task](https://github.com/AdguardTeam/AdguardForMac/issues/617).

**Comment by zzebrum** [comment]
https://github.com/StylishThemes/GitHub-Dark-Script/  currently it's not working because of GM4 async API #170 

[Taiwanese script](https://greasyfork.org/en/scripts/370155-%E8%B7%B3%E9%81%8E%E5%8B%95%E7%95%AB%E7%98%8B%E5%BB%A3%E5%91%8A/code) is not working:
https://uploads.adguard.com/Windows_10_32_bit_rus_2019-06-27_19-16-14.png

Other scripts seem to be working.

**Comment by ameshkov** [comment]
GM4 API will be added in v1.6
