### ISSUE TITLE
Userscripts implementation checklist

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#427]
* [x] `@require` meta data must be stored as a list of `{ "url": "", "content": "" }` objects
* [x] Make sure that `@connect` works: https://tampermonkey.net/documentation.php#_connect
* [x] Make sure that `@grant` permissions are enforced on the server-side, not just by the client-side: https://tampermonkey.net/documentation.php#_grant
* [x] Make sure that `@noframes` is properly implemented by the client-side: https://tampermonkey.net/documentation.php#_noframes

**Comment by szolin** [comment]
todo list for `@connect`:
. domains like tampermonkey.net (this will also allow all sub-domains)
. sub-domains i.e. safari.tampermonkey.net
. self to whitelist the domain the script is currently running at
. localhost to access the localhost
. 1.2.3.4 to connect to an IP address

**Comment by szolin** [comment]
core/pull-requests/591

**Comment by sfionov** [comment]
> Make sure that @noframes is properly implemented by the client-side: https://tampermonkey.net/documentation.php#_noframes

Seems that there is a bug. Currently this check condition (isAllowedToExecute) is calculated but is not used in run() function.

**Comment by ameshkov** [comment]
Summoning @maximtop here
